export enum MealCategories {
    DESSERTS_ICECREAM = 'DESSERTS_ICECREAM',
    COLD_DRINKS = 'COLD_DRINKS',
    HOT_DRINKS = 'HOT_DRINKS',
    BURGERS = 'BURGERS',
    WRAPS_SALADS = 'WRAPS_SALADS',
    FRIES_SIDES = 'FRIES_SIDES',
    CHICKEN = 'CHICKEN'
  }